image: Visual Studio 2019
configuration: Debug
before_build:
- cmd: nuget sources add -name MetaBrainzBuildSdk -source https://ci.appveyor.com/nuget/metabrainz-build-9ykcqeg83aaa
- cmd: dotnet restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  parallel: true
  verbosity: minimal
