image: Visual Studio 2019
configuration: Debug
before_build:
- cmd: dotnet restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  parallel: true
  verbosity: minimal
